### ISSUE TITLE
Pact verification throws error if there are no pacts to be verified

### ISSUE THREAD

**Issue by aislaapps** [reecetech/pactman#76] opened 2019-11-11 01:14 UTC
The following error is thrown if there are no contracts on the broker for a provider when a service is only a consumer.
```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
.tox/venv/lib/python3.7/site-packages/_pytest/python.py:1141: in _idval
    generated_id = idfn(val)
.tox/venv/lib/python3.7/site-packages/pactman/verifier/pytest_plugin.py:106: in test_id
    interaction, _ = identifier
E   TypeError: cannot unpack non-iterable object object

The above exception was the direct cause of the following exception:
.tox/venv/lib/python3.7/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
.tox/venv/lib/python3.7/site-packages/pluggy/manager.py:92: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
.tox/venv/lib/python3.7/site-packages/pluggy/manager.py:86: in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
.tox/venv/lib/python3.7/site-packages/_pytest/python.py:234: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
.tox/venv/lib/python3.7/site-packages/_pytest/python.py:403: in _genfunctions
    self.ihook.pytest_generate_tests.call_extra(methods, dict(metafunc=metafunc))
.tox/venv/lib/python3.7/site-packages/pluggy/hooks.py:324: in call_extra
    return self(**kwargs)
.tox/venv/lib/python3.7/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
.tox/venv/lib/python3.7/site-packages/pluggy/manager.py:92: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
.tox/venv/lib/python3.7/site-packages/pluggy/manager.py:86: in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
.tox/venv/lib/python3.7/site-packages/pactman/verifier/pytest_plugin.py:134: in pytest_generate_tests
    metafunc.parametrize("pact_verifier", flatten_pacts(pacts), ids=test_id, indirect=True)
.tox/venv/lib/python3.7/site-packages/_pytest/python.py:975: in parametrize
    ids = self._resolve_arg_ids(argnames, ids, parameters, item=self.definition)
.tox/venv/lib/python3.7/site-packages/_pytest/python.py:1029: in _resolve_arg_ids
    ids = idmaker(argnames, parameters, idfn, ids, self.config, item=item)
.tox/venv/lib/python3.7/site-packages/_pytest/python.py:1185: in idmaker
    for valindex, parameterset in enumerate(parametersets)
.tox/venv/lib/python3.7/site-packages/_pytest/python.py:1185: in <listcomp>
    for valindex, parameterset in enumerate(parametersets)
.tox/venv/lib/python3.7/site-packages/_pytest/python.py:1175: in _idvalset
    for val, argname in zip(parameterset.values, argnames)
.tox/venv/lib/python3.7/site-packages/_pytest/python.py:1175: in <listcomp>
    for val, argname in zip(parameterset.values, argnames)
.tox/venv/lib/python3.7/site-packages/_pytest/python.py:1148: in _idval
    raise ValueError(msg) from e
E   ValueError: tests/verify_pacts.py::test_pacts: error raised while trying to determine id of parameter 'pact_verifier' at position 0
```

**Comment by jkar32** [comment] 2019-11-21 06:13
Hi @aislaapps ,

This was found and left in place to protect the service from the scenario where the service has the wrong consumer names resulting in the pact validation looking like it is passing when in reality it did not verify any pacts. We ran into this issue a while back and is on the backlog to find out the best way to deal with this issue.

How we solved this was to push up a dummy pact, in our case against the services version endpoint and then removing that dummy pact when we had consumers.

**Comment by ryallsa** [comment] 2020-04-10 01:25
Thanks for contacting Registers of Scotland, your email has been delivered to your intended recipient(s), who will be in touch as soon as they can.

In order to focus on safeguarding the wellbeing of our staff, maintaining our essential business activity, and operating in accordance with government guidelines during this public health emergency, we ask that you direct your enquiries as follows:

A specific case or enquiry – please resend your email to our Customer Services<mailto:customer.services@ros.gov.uk> team who will be in touch.

Any other general enquiry – please resend your email to Covid19enquiries@ros.gov.uk so it can be directed to the correct person.

Thank You

- - - - - - - - - - - - - - - - - - -
Registers of Scotland
- - - - - - - - - - - - - - - - - - -

www.ros.gov.uk<https://www.ros.gov.uk>

[cid:imagec1553f.PNG@709f9365.44aec63a]<https://www.ros.gov.uk/>    [cid:image031627.PNG@b99156a1.44821e50] <https://www.facebook.com/registersofscotland/>   [cid:image826115.PNG@a8f5383a.488b9567] <https://twitter.com/RegistersOfScot>   [cid:image376d28.PNG@4d8b4736.449cc6d9] <https://www.youtube.com/channel/UCsvdb1Mw7n-shANwtFxrDMQ>   [cid:image57c458.PNG@99c01ad8.45bd8e72] <https://www.linkedin.com/authwall?trk=gf&trkInfo=AQEFPBtu7CCWwQAAAWNewfqoDlR1tdKRE7wGUu67suRzsyti8TMecqKnr1l97Cm06GPZkKXX2TXzf5g1bQO13VHKbYipr9Tf136ULQZRIGWkYOfOjp8PupaH9JDvdmTdxeUFykI=&originalReferer=&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fregisters-of-scotland>

Please consider the environment – do you really need to print this email?

This e-mail (and any files or other attachments transmitted with it) is intended solely for the attention of the addressee(s). Unauthorised use, disclosure, storage, copying or distribution of any part of this e-mail is not permitted. If you are not the intended recipient please destroy the email, remove any copies from your system and inform the sender immediately by return. 

Registers of Scotland does not accept any liability or responsibility for any damage caused by any virus transmitted by this email or for changes made to this e-mail after it was sent. 
All communications to or from Registers of Scotland may be automatically logged, monitored and/or recorded in order to secure the effective operation of the system and for other lawful purposes. The views or opinions contained within this e-mail may not necessarily reflect those of the Keeper of the Registers of Scotland.

**Closed as completed** 2020-04-10 01:24 UTC
