### ISSUE TITLE
Custom Headers for pytest pactman verifier

### ISSUE THREAD

**Issue by S-Mann** [reecetech/pactman#86] opened 2020-04-23 20:19 UTC
I see you have custom headers in your CLI code but there is no way to pass custom headers in the pytest plugin. I am updating the code and will raise a PR for it.

**Comment by tpmullan** [comment] 2020-04-23 20:45
This issue is also effecting my project.  Thanks for the fix!  I hope they merge this soon

**Comment by ryallsa** [comment] 2020-04-23 20:46
Thanks for contacting Registers of Scotland, your email has been delivered to your intended recipient(s).

During this time we are ensuring that group mailboxes associated with our departments and business functions are being actively monitored and enquiries to them will receive a response.

If you have emailed an individual employee email address, we ask that you direct your enquiries as follows:

A specific case or enquiry – please send all enquiries relating to a specific case to our  Customer Services<mailto:customer.services@ros.gov.uk> team, who will be in touch.

COVID 19 general enquiry – our website is regularly updated with all the latest information and updates<https://www.ros.gov.uk/coronavirus-covid-19> in relation to Coronavirus. If you have a COVID-19 related enquiry that is not answered on our webpage then please email Covid19enquiries@ros.gov.uk<mailto:Covid19enquiries@ros.gov.uk>, where your enquiry will be directed to the most appropriate/available person to respond.

Any other general enquiry – If you have concerns that your intended recipient has not received your enquiry then please resend your email to Covid19enquiries@ros.gov.uk<mailto:Covid19enquiries@ros.gov.uk> so it can be directed to the most appropriate/available person to respond.

Thank You

- - - - - - - - - - - - - - - - - - -
Registers of Scotland
- - - - - - - - - - - - - - - - - - -

www.ros.gov.uk<https://www.ros.gov.uk>

[cid:imageb0e1c5.PNG@29c390f7.4ab80d9b]<https://www.ros.gov.uk/>    [cid:image98d5cc.PNG@04359bce.46923e2c] <https://www.facebook.com/registersofscotland/>   [cid:image1b4ff9.PNG@efd588bd.4a8c4eb7] <https://twitter.com/RegistersOfScot>   [cid:image4dda1d.PNG@fff6c819.4ea1c372] <https://www.youtube.com/channel/UCsvdb1Mw7n-shANwtFxrDMQ>   [cid:imaged165c9.PNG@9e2092a4.40bf52fe] <https://www.linkedin.com/authwall?trk=gf&trkInfo=AQEFPBtu7CCWwQAAAWNewfqoDlR1tdKRE7wGUu67suRzsyti8TMecqKnr1l97Cm06GPZkKXX2TXzf5g1bQO13VHKbYipr9Tf136ULQZRIGWkYOfOjp8PupaH9JDvdmTdxeUFykI=&originalReferer=&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fregisters-of-scotland>

Please consider the environment – do you really need to print this email?

This e-mail (and any files or other attachments transmitted with it) is intended solely for the attention of the addressee(s). Unauthorised use, disclosure, storage, copying or distribution of any part of this e-mail is not permitted. If you are not the intended recipient please destroy the email, remove any copies from your system and inform the sender immediately by return. 

Registers of Scotland does not accept any liability or responsibility for any damage caused by any virus transmitted by this email or for changes made to this e-mail after it was sent. 
All communications to or from Registers of Scotland may be automatically logged, monitored and/or recorded in order to secure the effective operation of the system and for other lawful purposes. The views or opinions contained within this e-mail may not necessarily reflect those of the Keeper of the Registers of Scotland.

**Closed as completed** 2020-04-27 05:45 UTC

**Comment by r1chardj0n3s** [comment] 2020-04-27 06:00
Released in 2.26.0
