### ISSUE TITLE
Monkeypatching during pact verification

### ISSUE THREAD

**Issue by thatguysimon** [reecetech/pactman#82] opened 2020-03-23 13:33 UTC
Hi all,
I have a quick question regarding this line in the readme:

> The test function may do any level of mocking and data setup using standard pytest fixtures - so mocking downstream APIs or other interactions within the provider may be done with **standard monkeypatching**.

What exactly is "standard monkeypatching" referring to?
- Is it `pytest`'s [monkeypatch fixture](https://docs.pytest.org/en/latest/monkeypatch.html)? If so, how would that work given that the service is running in a separate process from pytest?
- Or is it "classic" monkeypatching where you dynamically modify functions/modules/classes?

Is there an example of this anywhere?

Thanks!
Simon.

**Comment by ryallsa** [comment] 2020-03-23 13:59
Thanks for contacting Registers of Scotland, your email has been delivered to your intended recipient(s), who will be in touch as soon as they can.

In order to focus on safeguarding the wellbeing of our staff, maintaining our essential business activity, and operating in accordance with government guidelines during this public health emergency, we ask that you direct your enquiries as follows:

A specific case or enquiry – please resend your email to our Customer Services<mailto:customer.services@ros.gov.uk> team who will be in touch.

Any other general enquiry – please resend your email to Covid19enquiries@ros.gov.uk so it can be directed to the correct person.

Thank You

- - - - - - - - - - - - - - - - - - -
Registers of Scotland
- - - - - - - - - - - - - - - - - - -

www.ros.gov.uk<https://www.ros.gov.uk>

[cid:image7a32bb.PNG@0a962f68.498d90f1]<https://www.ros.gov.uk/>    [cid:imagee356e7.PNG@8ba99951.4fba15dd] <https://www.facebook.com/registersofscotland/>   [cid:image7408c8.PNG@60d3a9ac.42a03f0b] <https://twitter.com/RegistersOfScot>   [cid:image440bcb.PNG@2aae296d.44863c5c] <https://www.youtube.com/channel/UCsvdb1Mw7n-shANwtFxrDMQ>   [cid:image3ee99d.PNG@20945322.41b6161b] <https://www.linkedin.com/authwall?trk=gf&trkInfo=AQEFPBtu7CCWwQAAAWNewfqoDlR1tdKRE7wGUu67suRzsyti8TMecqKnr1l97Cm06GPZkKXX2TXzf5g1bQO13VHKbYipr9Tf136ULQZRIGWkYOfOjp8PupaH9JDvdmTdxeUFykI=&originalReferer=&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fregisters-of-scotland>

Please consider the environment – do you really need to print this email?

This e-mail (and any files or other attachments transmitted with it) is intended solely for the attention of the addressee(s). Unauthorised use, disclosure, storage, copying or distribution of any part of this e-mail is not permitted. If you are not the intended recipient please destroy the email, remove any copies from your system and inform the sender immediately by return. 

Registers of Scotland does not accept any liability or responsibility for any damage caused by any virus transmitted by this email or for changes made to this e-mail after it was sent. 
All communications to or from Registers of Scotland may be automatically logged, monitored and/or recorded in order to secure the effective operation of the system and for other lawful purposes. The views or opinions contained within this e-mail may not necessarily reflect those of the Keeper of the Registers of Scotland.

**Comment by r1chardj0n3s** [comment] 2020-04-10 01:10
Yes, any monkeypatching mechanism you would normally use in a unit test is appropriate.

**Comment by ryallsa** [comment] 2020-04-10 01:11
Thanks for contacting Registers of Scotland, your email has been delivered to your intended recipient(s), who will be in touch as soon as they can.

In order to focus on safeguarding the wellbeing of our staff, maintaining our essential business activity, and operating in accordance with government guidelines during this public health emergency, we ask that you direct your enquiries as follows:

A specific case or enquiry – please resend your email to our Customer Services<mailto:customer.services@ros.gov.uk> team who will be in touch.

Any other general enquiry – please resend your email to Covid19enquiries@ros.gov.uk so it can be directed to the correct person.

Thank You

- - - - - - - - - - - - - - - - - - -
Registers of Scotland
- - - - - - - - - - - - - - - - - - -

www.ros.gov.uk<https://www.ros.gov.uk>

[cid:imaged38e0d.PNG@c24033f4.4ebd3a2a]<https://www.ros.gov.uk/>    [cid:image504568.PNG@8aa70b36.4bbf4681] <https://www.facebook.com/registersofscotland/>   [cid:image00cf4c.PNG@179aaa82.4489f893] <https://twitter.com/RegistersOfScot>   [cid:imagef1b33c.PNG@4e5f679a.44867c67] <https://www.youtube.com/channel/UCsvdb1Mw7n-shANwtFxrDMQ>   [cid:imaged228ee.PNG@0e5b9a8f.41a6e363] <https://www.linkedin.com/authwall?trk=gf&trkInfo=AQEFPBtu7CCWwQAAAWNewfqoDlR1tdKRE7wGUu67suRzsyti8TMecqKnr1l97Cm06GPZkKXX2TXzf5g1bQO13VHKbYipr9Tf136ULQZRIGWkYOfOjp8PupaH9JDvdmTdxeUFykI=&originalReferer=&sessionRedirect=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fregisters-of-scotland>

Please consider the environment – do you really need to print this email?

This e-mail (and any files or other attachments transmitted with it) is intended solely for the attention of the addressee(s). Unauthorised use, disclosure, storage, copying or distribution of any part of this e-mail is not permitted. If you are not the intended recipient please destroy the email, remove any copies from your system and inform the sender immediately by return. 

Registers of Scotland does not accept any liability or responsibility for any damage caused by any virus transmitted by this email or for changes made to this e-mail after it was sent. 
All communications to or from Registers of Scotland may be automatically logged, monitored and/or recorded in order to secure the effective operation of the system and for other lawful purposes. The views or opinions contained within this e-mail may not necessarily reflect those of the Keeper of the Registers of Scotland.

**Closed as completed by r1chardj0n3s** 2020-04-10 01:10 UTC
